"""Top_5_Overhaul

Revision ID: bec09f4c00ab
Revises: 0001
Create Date: 2026-03-18 18:24:11.729725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec09f4c00ab'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_opt_out_info_scorecard_id', 'opt_out_info', ['scorecard_id'])
    op.drop_constraint(op.f('opt_out_info_scorecard_id_fkey'), 'opt_out_info', type_='foreignkey')
    op.create_foreign_key(None, 'opt_out_info', 'scorecards', ['scorecard_id'], ['id'])
    op.create_unique_constraint('uq_risk_categories_scorecard_id_category_key', 'risk_categories', ['scorecard_id', 'category_key'])
    op.drop_constraint(op.f('risk_categories_scorecard_id_fkey'), 'risk_categories', type_='foreignkey')
    op.create_foreign_key(None, 'risk_categories', 'scorecards', ['scorecard_id'], ['id'])
    op.add_column('scan_jobs', sa.Column('submitted_url', sa.Text(), nullable=True))
    op.add_column('scan_jobs', sa.Column('brand_slug', sa.String(length=255), nullable=True))
    op.drop_column('scan_jobs', 'brand_name')
    op.drop_constraint(op.f('scorecards_brand_id_fkey'), 'scorecards', type_='foreignkey')
    op.create_foreign_key(None, 'scorecards', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scorecards', type_='foreignkey')
    op.create_foreign_key(op.f('scorecards_brand_id_fkey'), 'scorecards', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.add_column('scan_jobs', sa.Column('brand_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('scan_jobs', 'brand_slug')
    op.drop_column('scan_jobs', 'submitted_url')
    op.drop_constraint(None, 'risk_categories', type_='foreignkey')
    op.create_foreign_key(op.f('risk_categories_scorecard_id_fkey'), 'risk_categories', 'scorecards', ['scorecard_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_risk_categories_scorecard_id_category_key', 'risk_categories', type_='unique')
    op.drop_constraint(None, 'opt_out_info', type_='foreignkey')
    op.create_foreign_key(op.f('opt_out_info_scorecard_id_fkey'), 'opt_out_info', 'scorecards', ['scorecard_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_opt_out_info_scorecard_id', 'opt_out_info', type_='unique')
    # ### end Alembic commands ###
